spring:
  kafka:
    one:
      # broker
      bootstrap-servers: 49.232.119.51:9092
      producer:
        group-id: honyeeProducer
      consumer:
        group-id: honyeeConsumer
        enable-auto-commit: false
      listener:
        ack-mode: MANUAL