logging:
  config: classpath:logback-spring-prod.xml

# 禁用文档
springdoc:
  api-docs:
    enabled: false

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1:3306/honyee?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: root



application:
  oss:
    url-protocol: https://
    endpoint: oss的endpoint
    bucket-name: xxxx
    folder-env: prod
    folder-root: honyee
    url-image: oss域名，末尾不要斜杠
    access-key-id: xxxx
    access-key-secret: xxxx
    client:
      protocol: https