logging:
  config: classpath:logback-spring-prod.xml

# 禁用文档
springdoc:
  api-docs:
    enabled: false

spring:
  redis:
    host: 127.0.0.1
    port: 6379
    password: redis..123
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:mysql://127.0.0.1/honyee?useUnicode=true&characterEncoding=utf8&useSSL=false&useLegacyDatetimeCode=false&serverTimezone=UTC&createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true
    username: root
    password: mysql..123